/**
 * Building types, as DATA.
 *
 * GENERATED by scripts/import-massings.mjs from docs/massings/. Do not edit by
 * hand — re-export the canvas and re-run `npm run import:massings`.
 *
 * The section drawing is never inline JSX. A `BuildingType` holds the massing
 * paths, the ground, the occupant glyphs and one anchor per arrow slot, and
 * `SectionDrawing` renders whichever record it is handed.
 *
 * `data-surface` in the canvas and `SurfaceSlot` here are the same names on
 * purpose. That is the contract between the drawing and the engine, and it is
 * why six massings need no renderer changes between them.
 */

import type { ArrowAnchor, BuildingType, BuildingTypeId, MassingPath } from './types';

const OFFICE_SHELL: MassingPath[] = [
  { d: 'M176 454 C 173 380 179 290 176 208 C 254 205 340 211 424 208 C 508 205 576 211 636 208 C 633 290 639 380 636 454 C 566 457 494 451 424 454 C 342 457 250 451 176 454 Z', role: 'shell' },
  { d: 'M164 208 C 264 205 366 211 466 208 C 534 206 588 210 648 208', role: 'shell' },
  { d: 'M176 454 C 250 451 342 457 424 454 C 494 451 566 457 636 454', role: 'shell' },
  { d: 'M177 466 C 251 463 342 469 424 466 C 494 463 565 469 635 466', role: 'floor-line' },
  { d: 'M176 290 C 250 287 342 293 424 290 C 494 287 566 293 636 290', role: 'floor-line' },
  { d: 'M176 372 C 250 369 342 375 424 372 C 494 369 566 375 636 372', role: 'floor-line' },
  { d: 'M636 236 C 610 233 584 239 558 236 C 555 254 561 266 558 278 C 584 281 610 275 636 278', role: 'aperture' },
  { d: 'M636 318 C 610 315 584 321 558 318 C 555 336 561 348 558 360 C 584 363 610 357 636 360', role: 'aperture' },
  { d: 'M176 236 C 200 233 224 239 248 236 C 245 254 251 266 248 278 C 224 281 200 275 176 278', role: 'aperture' },
];

const OFFICE_GLYPHS: MassingPath[] = [
  { d: 'M300 411 C 301 422 299 430 300 438 M288 418 C 293 415 307 415 312 418 M300 438 L 292 452 M300 438 L 308 452', role: 'glyph' },
  { d: 'M420 230 C 421 244 419 254 420 262', role: 'glyph-light' },
  { d: 'M406 276 C 409 267 414 262 420 262 C 426 262 431 267 434 276 C 425 278 415 274 406 276 Z', role: 'glyph' },
  { d: 'M460 412 C 474 409 488 415 502 412 C 499 422 505 430 502 440 C 488 443 474 437 460 440 C 463 430 457 422 460 412 Z', role: 'glyph' },
  { d: 'M528 412 C 542 409 556 415 570 412 C 567 422 573 430 570 440 C 556 443 542 437 528 440 C 531 430 525 422 528 412 Z', role: 'glyph' },
  { d: 'M533.6 417.5 L 564.4 417.5 M533.6 426 L 555.7 426 M533.6 434.5 L 564.4 434.5', role: 'glyph-light' },
];

const OFFICE_ANCHORS: ArrowAnchor[] = [
  { slot: 'gain-people', x: 300, y: 396, rotate: -108 },
  { slot: 'gain-lighting', x: 406, y: 272, rotate: 174 },
  { slot: 'gain-misc-equipment', x: 481, y: 406, rotate: -72 },
  { slot: 'loss-roof', x: 400, y: 202, rotate: -90 },
  { slot: 'loss-walls', x: 176, y: 336, rotate: 180 },
  { slot: 'loss-windows', x: 636, y: 258, rotate: 0 },
  { slot: 'loss-ground-floor', x: 470, y: 470, rotate: 90 },
  { slot: 'loss-exposed-floor', x: 222, y: 470, rotate: 90 },
  { slot: 'gain-it-equipment', x: 549, y: 406, rotate: -72 },
];

export const OFFICE: BuildingType = {
  id: 'office',
  label: 'Office',
  viewBox: '-135 -49 1082 770',
  shell: OFFICE_SHELL,
  glyphs: OFFICE_GLYPHS,
  soil: [
    { x: 270, y: 454, width: 610, height: 346 },
    { x: -120, y: 556, width: 1000, height: 244 },
  ],
  anchors: OFFICE_ANCHORS,
};

const SCHOOL_SHELL: MassingPath[] = [
  { d: 'M158 462 C 155 404 161 340 158 286 C 226 283 300 289 368 286 C 365 322 371 350 368 376 C 442 373 524 379 604 376 C 601 404 607 436 604 462 C 530 465 448 459 368 462 C 296 465 226 459 158 462 Z', role: 'shell' },
  { d: 'M146 286 C 218 283 292 289 364 286 C 394 285 410 288 380 288', role: 'shell' },
  { d: 'M356 376 C 438 373 526 379 616 376', role: 'shell' },
  { d: 'M158 462 C 226 459 296 465 368 462 C 448 459 530 465 604 462', role: 'shell' },
  { d: 'M159 474 C 227 471 296 477 368 474 C 448 471 529 477 603 474', role: 'floor-line' },
  { d: 'M226 240 C 226 256 226 270 226 286 M300 240 C 300 256 300 270 300 286', role: 'shell' },
  { d: 'M214 240 C 244 237 274 243 304 240 C 288 224 268 214 258 212 C 246 216 230 226 214 240 Z', role: 'shell' },
  { d: 'M158 322 C 182 319 206 325 230 322 C 227 344 233 364 230 382 C 206 385 182 379 158 382', role: 'aperture' },
  { d: 'M604 404 C 578 401 552 407 526 404 C 523 420 529 430 526 440 C 552 443 578 437 604 440', role: 'aperture' },
];

const SCHOOL_GLYPHS: MassingPath[] = [
  { d: 'M284 405 C 285 416 283 424 284 432 M272 412 C 277 409 291 409 296 412 M284 432 L 276 446 M284 432 L 292 446', role: 'glyph' },
  { d: 'M470 400 C 471 414 469 424 470 432', role: 'glyph-light' },
  { d: 'M456 446 C 459 437 464 432 470 432 C 476 432 481 437 484 446 C 475 448 465 444 456 446 Z', role: 'glyph' },
  { d: 'M198 412 C 212 409 226 415 240 412 C 237 422 243 430 240 440 C 226 443 212 437 198 440 C 201 430 195 422 198 412 Z', role: 'glyph' },
  { d: 'M266 412 C 280 409 294 415 308 412 C 305 422 311 430 308 440 C 294 443 280 437 266 440 C 269 430 263 422 266 412 Z', role: 'glyph' },
  { d: 'M271.6 417.5 L 302.4 417.5 M271.6 426 L 293.7 426 M271.6 434.5 L 302.4 434.5', role: 'glyph-light' },
];

const SCHOOL_ANCHORS: ArrowAnchor[] = [
  { slot: 'gain-people', x: 284, y: 390, rotate: -98 },
  { slot: 'gain-lighting', x: 456, y: 442, rotate: 178 },
  { slot: 'gain-misc-equipment', x: 219, y: 406, rotate: -118 },
  { slot: 'loss-roof', x: 500, y: 370, rotate: -90 },
  { slot: 'loss-walls', x: 604, y: 418, rotate: 0 },
  { slot: 'loss-windows', x: 158, y: 352, rotate: 180 },
  { slot: 'loss-ground-floor', x: 500, y: 478, rotate: 90 },
  { slot: 'loss-exposed-floor', x: 206, y: 478, rotate: 90 },
  { slot: 'gain-it-equipment', x: 287, y: 406, rotate: -118 },
];

export const SCHOOL: BuildingType = {
  id: 'school',
  label: 'School',
  viewBox: '-153 101 1068 628',
  shell: SCHOOL_SHELL,
  glyphs: SCHOOL_GLYPHS,
  soil: [
    { x: 254, y: 462, width: 626, height: 338 },
    { x: -120, y: 560, width: 1000, height: 240 },
  ],
  anchors: SCHOOL_ANCHORS,
};

const LAB_SHELL: MassingPath[] = [
  { d: 'M186 458 C 183 386 189 300 186 224 C 258 221 336 227 410 224 C 484 221 552 227 614 224 C 611 300 617 386 614 458 C 544 461 470 455 410 458 C 336 461 258 455 186 458 Z', role: 'shell' },
  { d: 'M174 224 C 270 221 372 227 470 224 C 526 222 566 226 626 224', role: 'shell' },
  { d: 'M186 458 C 258 455 336 461 410 458 C 470 455 544 461 614 458', role: 'shell' },
  { d: 'M187 470 C 259 467 336 473 410 470 C 470 467 543 473 613 470', role: 'floor-line' },
  { d: 'M186 342 C 258 339 336 345 410 342 C 470 339 544 345 614 342', role: 'floor-line' },
  { d: 'M230 224 C 228 208 232 196 230 180 C 250 177 272 183 292 180 C 290 196 294 208 292 224', role: 'aperture' },
  { d: 'M340 224 C 338 206 342 190 340 172 C 348 169 358 175 366 172 C 364 190 368 206 366 224', role: 'aperture' },
  { d: 'M340 172 C 338 158 348 150 360 152', role: 'shell' },
  { d: 'M614 254 C 588 251 562 257 536 254 C 533 272 539 288 536 306 C 562 309 588 303 614 306', role: 'aperture' },
  { d: 'M186 254 C 210 251 234 257 258 254 C 255 272 261 288 258 306 C 234 309 210 303 186 306', role: 'aperture' },
];

const LAB_GLYPHS: MassingPath[] = [
  { d: 'M306 399 C 307 410 305 418 306 426 M294 406 C 299 403 313 403 318 406 M306 426 L 298 440 M306 426 L 314 440', role: 'glyph' },
  { d: 'M410 250 C 411 264 409 274 410 282', role: 'glyph-light' },
  { d: 'M396 296 C 399 287 404 282 410 282 C 416 282 421 287 424 296 C 415 298 405 294 396 296 Z', role: 'glyph' },
  { d: 'M470 396 C 488 393 506 399 524 396 C 521 408 527 420 524 432 C 506 435 488 429 470 432 C 473 420 467 408 470 396 Z', role: 'glyph' },
  { d: 'M480 410 C 492 410 500 410 512 410', role: 'glyph-light' },
  { d: 'M538 396 C 556 393 574 399 592 396 C 589 408 595 420 592 432 C 574 435 556 429 538 432 C 541 420 535 408 538 396 Z', role: 'glyph' },
  { d: 'M545.8 403.5 L 584.2 403.5 M545.8 414 L 573.4 414 M545.8 424.5 L 584.2 424.5', role: 'glyph-light' },
];

const LAB_ANCHORS: ArrowAnchor[] = [
  { slot: 'gain-people', x: 306, y: 384, rotate: -108 },
  { slot: 'gain-lighting', x: 396, y: 292, rotate: 174 },
  { slot: 'gain-misc-equipment', x: 497, y: 390, rotate: -74 },
  { slot: 'loss-roof', x: 460, y: 218, rotate: -90 },
  { slot: 'loss-walls', x: 186, y: 392, rotate: 180 },
  { slot: 'loss-windows', x: 614, y: 280, rotate: 0 },
  { slot: 'loss-ground-floor', x: 480, y: 474, rotate: 90 },
  { slot: 'loss-exposed-floor', x: 230, y: 474, rotate: 90 },
  { slot: 'gain-it-equipment', x: 565, y: 390, rotate: -74 },
];

export const LAB: BuildingType = {
  id: 'lab',
  label: 'Laboratory',
  viewBox: '-134 -33 1059 758',
  shell: LAB_SHELL,
  glyphs: LAB_GLYPHS,
  soil: [
    { x: 276, y: 458, width: 604, height: 342 },
    { x: -120, y: 558, width: 1000, height: 242 },
  ],
  anchors: LAB_ANCHORS,
};

const CIVIC_SHELL: MassingPath[] = [
  { d: 'M170 470 C 167 428 173 380 170 336 C 170 300 176 268 174 244 C 256 241 348 247 430 244 C 512 241 582 247 626 244 C 624 268 630 300 630 336 C 627 380 633 428 630 470 C 556 473 474 467 400 470 C 322 473 244 467 170 470 Z', role: 'shell' },
  { d: 'M160 244 C 260 241 364 247 466 244 C 528 242 580 246 640 244', role: 'shell' },
  { d: 'M186 244 C 218 208 274 168 330 152 C 388 168 444 208 476 244', role: 'shell' },
  { d: 'M222 244 C 222 288 222 320 222 356 M262 244 C 262 288 262 320 262 356 M302 244 C 302 288 302 320 302 356 M342 244 C 342 288 342 320 342 356 M382 244 C 382 288 382 320 382 356', role: 'shell' },
  { d: 'M170 366 C 250 363 322 369 400 366 C 470 363 556 369 630 366', role: 'aperture' },
  { d: 'M170 470 C 244 467 322 473 400 470 C 474 467 556 473 630 470', role: 'shell' },
  { d: 'M171 482 C 245 479 322 485 400 482 C 474 479 555 485 629 482', role: 'floor-line' },
  { d: 'M630 396 C 598 393 566 399 534 396 C 531 414 537 430 534 448 C 566 451 598 445 630 448', role: 'aperture' },
  { d: 'M440 296 C 464 293 488 299 512 296 C 509 314 515 330 512 348 C 488 351 464 345 440 348', role: 'aperture' },
];

const CIVIC_GLYPHS: MassingPath[] = [
  { d: 'M330 409 C 331 420 329 428 330 436 M318 416 C 323 413 337 413 342 416 M330 436 L 322 450 M330 436 L 338 450', role: 'glyph' },
  { d: 'M430 288 C 431 302 429 312 430 320', role: 'glyph-light' },
  { d: 'M416 334 C 419 325 424 320 430 320 C 436 320 441 325 444 334 C 435 336 425 332 416 334 Z', role: 'glyph' },
  { d: 'M470 408 C 484 405 498 411 512 408 C 509 418 515 426 512 436 C 498 439 484 433 470 436 C 473 426 467 418 470 408 Z', role: 'glyph' },
  { d: 'M538 408 C 552 405 566 411 580 408 C 577 418 583 426 580 436 C 566 439 552 433 538 436 C 541 426 535 418 538 408 Z', role: 'glyph' },
  { d: 'M543.6 413.5 L 574.4 413.5 M543.6 422 L 565.7 422 M543.6 430.5 L 574.4 430.5', role: 'glyph-light' },
];

const CIVIC_ANCHORS: ArrowAnchor[] = [
  { slot: 'gain-people', x: 330, y: 394, rotate: -112 },
  { slot: 'gain-lighting', x: 416, y: 330, rotate: 176 },
  { slot: 'gain-misc-equipment', x: 491, y: 402, rotate: -70 },
  { slot: 'loss-roof', x: 390, y: 196, rotate: -64 },
  { slot: 'loss-walls', x: 170, y: 300, rotate: 180 },
  { slot: 'loss-windows', x: 630, y: 422, rotate: 0 },
  { slot: 'loss-ground-floor', x: 500, y: 486, rotate: 90 },
  { slot: 'loss-exposed-floor', x: 216, y: 486, rotate: 90 },
  { slot: 'gain-it-equipment', x: 559, y: 402, rotate: -70 },
];

export const CIVIC: BuildingType = {
  id: 'civic',
  label: 'Civic',
  viewBox: '-141 -55 1082 792',
  shell: CIVIC_SHELL,
  glyphs: CIVIC_GLYPHS,
  soil: [
    { x: 264, y: 470, width: 616, height: 330 },
    { x: -120, y: 562, width: 1000, height: 238 },
  ],
  anchors: CIVIC_ANCHORS,
};

const MULTIFAMILY_SHELL: MassingPath[] = [
  { d: 'M212 470 C 209 380 215 272 212 164 C 280 161 356 167 424 164 C 492 161 550 167 600 164 C 597 272 603 380 600 470 C 542 473 484 467 424 470 C 356 473 282 467 212 470 Z', role: 'shell' },
  { d: 'M200 164 C 288 161 378 167 466 164 C 522 162 562 166 612 164', role: 'shell' },
  { d: 'M212 470 C 282 467 356 473 424 470 C 484 467 542 473 600 470', role: 'shell' },
  { d: 'M213 482 C 283 479 356 485 424 482 C 484 479 541 485 599 482', role: 'floor-line' },
  { d: 'M212 240 C 282 237 356 243 424 240 C 484 237 542 243 600 240 M212 316 C 282 313 356 319 424 316 C 484 313 542 319 600 316 M212 392 C 282 389 356 395 424 392 C 484 389 542 395 600 392', role: 'floor-line' },
  { d: 'M600 190 C 578 187 556 193 534 190 C 531 204 537 214 534 224 C 556 227 578 221 600 224 M600 266 C 578 263 556 269 534 266 C 531 280 537 290 534 300 C 556 303 578 297 600 300 M600 342 C 578 339 556 345 534 342 C 531 356 537 366 534 376 C 556 379 578 373 600 376', role: 'aperture' },
  { d: 'M212 190 C 232 187 252 193 272 190 C 269 204 275 214 272 224 C 252 227 232 221 212 224 M212 342 C 232 339 252 345 272 342 C 269 356 275 366 272 376 C 252 379 232 373 212 376', role: 'aperture' },
];

const MULTIFAMILY_GLYPHS: MassingPath[] = [
  { d: 'M316 427 C 317 438 315 446 316 454 M304 434 C 309 431 323 431 328 434 M316 454 L 308 468 M316 454 L 324 468', role: 'glyph' },
  { d: 'M420 186 C 421 200 419 210 420 218', role: 'glyph-light' },
  { d: 'M406 232 C 409 223 414 218 420 218 C 426 218 431 223 434 232 C 425 234 415 230 406 232 Z', role: 'glyph' },
  { d: 'M466 428 C 480 425 494 431 508 428 C 505 438 511 446 508 456 C 494 459 480 453 466 456 C 469 446 463 438 466 428 Z', role: 'glyph' },
  { d: 'M534 428 C 548 425 562 431 576 428 C 573 438 579 446 576 456 C 562 459 548 453 534 456 C 537 446 531 438 534 428 Z', role: 'glyph' },
  { d: 'M539.6 433.5 L 570.4 433.5 M539.6 442 L 561.7 442 M539.6 450.5 L 570.4 450.5', role: 'glyph-light' },
];

const MULTIFAMILY_ANCHORS: ArrowAnchor[] = [
  { slot: 'gain-people', x: 316, y: 412, rotate: -108 },
  { slot: 'gain-lighting', x: 406, y: 228, rotate: 174 },
  { slot: 'gain-misc-equipment', x: 487, y: 422, rotate: -72 },
  { slot: 'loss-roof', x: 400, y: 158, rotate: -90 },
  { slot: 'loss-walls', x: 212, y: 290, rotate: 180 },
  { slot: 'loss-windows', x: 600, y: 207, rotate: 0 },
  { slot: 'loss-ground-floor', x: 474, y: 486, rotate: 90 },
  { slot: 'loss-exposed-floor', x: 252, y: 486, rotate: 90 },
  { slot: 'gain-it-equipment', x: 555, y: 422, rotate: -72 },
];

export const MULTIFAMILY: BuildingType = {
  id: 'multifamily',
  label: 'Multi-family',
  viewBox: '-134 -93 1045 830',
  shell: MULTIFAMILY_SHELL,
  glyphs: MULTIFAMILY_GLYPHS,
  soil: [
    { x: 286, y: 470, width: 594, height: 330 },
    { x: -120, y: 562, width: 1000, height: 238 },
  ],
  anchors: MULTIFAMILY_ANCHORS,
};

const HOME_SHELL: MassingPath[] = [
  { d: 'M190 430 C 187 372 193 306 190 250 C 254 213 320 175 380 162 C 442 176 508 214 570 250 C 567 310 573 374 570 430 C 508 433 442 427 380 430 C 318 433 252 427 190 430 Z', role: 'shell' },
  { d: 'M170 262 C 240 218 312 176 380 154 C 450 178 522 220 590 262', role: 'shell' },
  { d: 'M190 430 C 252 427 318 433 380 430 C 442 427 508 433 570 430', role: 'shell' },
  { d: 'M191 442 C 253 439 318 445 380 442 C 442 439 507 445 569 442', role: 'floor-line' },
  { d: 'M184 352 C 190 349 196 355 202 352 C 205 374 199 394 202 412 C 196 415 190 409 184 412', role: 'aperture' },
  { d: 'M570 276 C 564 273 558 279 552 276 C 549 298 555 318 552 336 C 558 339 564 333 570 336', role: 'aperture' },
];

const HOME_GLYPHS: MassingPath[] = [
  { d: 'M320 391 C 321 402 319 410 320 418 M308 398 C 313 395 327 395 332 398 M320 418 L 312 432 M320 418 L 328 432', role: 'glyph' },
  { d: 'M400 268 C 401 282 399 292 400 300', role: 'glyph-light' },
  { d: 'M386 314 C 389 305 394 300 400 300 C 406 300 411 305 414 314 C 405 316 395 312 386 314 Z', role: 'glyph' },
  { d: 'M456 396 C 470 393 484 399 498 396 C 495 406 501 414 498 424 C 484 427 470 421 456 424 C 459 414 453 406 456 396 Z', role: 'glyph' },
  { d: 'M524 396 C 538 393 552 399 566 396 C 563 406 569 414 566 424 C 552 427 538 421 524 424 C 527 414 521 406 524 396 Z', role: 'glyph' },
  { d: 'M529.6 401.5 L 560.4 401.5 M529.6 410 L 551.7 410 M529.6 418.5 L 560.4 418.5', role: 'glyph-light' },
];

const HOME_ANCHORS: ArrowAnchor[] = [
  { slot: 'gain-people', x: 320, y: 376, rotate: -108 },
  { slot: 'gain-lighting', x: 386, y: 308, rotate: 172 },
  { slot: 'gain-misc-equipment', x: 477, y: 390, rotate: -72 },
  { slot: 'loss-roof', x: 480, y: 206, rotate: -62 },
  { slot: 'loss-walls', x: 190, y: 296, rotate: 180 },
  { slot: 'loss-windows', x: 570, y: 306, rotate: 0 },
  { slot: 'loss-ground-floor', x: 470, y: 446, rotate: 90 },
  { slot: 'loss-exposed-floor', x: 240, y: 446, rotate: 90 },
  { slot: 'gain-it-equipment', x: 545, y: 390, rotate: -72 },
];

export const HOME: BuildingType = {
  id: 'home',
  label: 'Single-family home',
  viewBox: '-134 -45 1028 742',
  shell: HOME_SHELL,
  glyphs: HOME_GLYPHS,
  soil: [
    { x: 300, y: 430, width: 580, height: 370 },
    { x: -120, y: 556, width: 1000, height: 244 },
  ],
  anchors: HOME_ANCHORS,
};

/** The ground line, per massing. */
export const GROUND_LINES: Record<BuildingTypeId, string> = {
  office: 'M880 455 C 640 452 520 457 400 454 C 366 453 300 456 271 454 L 270 500 C 273 528 267 542 270 557 C 180 554 90 559 -120 556',
  school: 'M880 463 C 640 460 520 465 400 462 C 350 461 290 464 255 462 L 254 506 C 257 534 251 548 254 561 C 170 558 84 563 -120 560',
  lab: 'M880 459 C 640 456 520 461 400 458 C 356 457 306 460 277 458 L 276 502 C 279 532 273 546 276 559 C 184 556 92 561 -120 558',
  civic: 'M880 471 C 640 468 520 473 400 470 C 350 469 296 472 265 470 L 264 512 C 267 538 261 550 264 563 C 176 560 88 565 -120 562',
  multifamily: 'M880 471 C 640 468 520 473 400 470 C 366 469 316 472 287 470 L 286 512 C 289 538 283 550 286 563 C 190 560 96 565 -120 562',
  home: 'M880 431 C 640 428 520 433 400 430 C 366 429 332 432 301 430 L 300 490 C 303 522 297 540 300 557 C 200 554 100 559 -120 556',
};

/** A person's head, which the glyph path deliberately leaves out. */
export const PERSON_HEADS: Record<BuildingTypeId, { cx: number; cy: number; r: number }> = {
  office: { cx: 300, cy: 404, r: 7 },
  school: { cx: 284, cy: 398, r: 7 },
  lab: { cx: 306, cy: 392, r: 7 },
  civic: { cx: 330, cy: 402, r: 7 },
  multifamily: { cx: 316, cy: 420, r: 7 },
  home: { cx: 320, cy: 384, r: 7 },
};

export const BUILDING_TYPES: readonly BuildingType[] = Object.freeze([
  OFFICE,
  SCHOOL,
  LAB,
  CIVIC,
  MULTIFAMILY,
  HOME,
]);

export function buildingType(id: BuildingTypeId): BuildingType {
  return BUILDING_TYPES.find((t) => t.id === id) ?? OFFICE;
}
