/**
 * Internal-gain presets, one per building type.
 *
 * GENERATED by scripts/import-gain-data.mjs from docs/gain-data/. Do not edit
 * by hand — edit the sheet and re-run `npm run import:gains`.
 *
 * Values are canonical SI: m² per person, W per person (sensible), W/m².
 * The sheet is collected in IP because that is what the standards publish;
 * the conversion happens once, in the importer.
 *
 * **The schedules are NOT from this data.** Sheet 2 has not come back yet, so
 * every preset below runs on the office profile, and `SCHEDULES_ARE_PROVISIONAL`
 * says so on the page. That matters more than it sounds: this tool's verdict is
 * decided between 04:00 and 07:00, so the overnight floor of a schedule moves
 * the answer more than the density it scales. A warehouse on an office lighting
 * profile is wrong in a way a user cannot see.
 */

export interface PresetDensity {
  /** Canonical SI. Null means the sheet left it blank: no default, not zero. */
  readonly value: number | null;
  readonly citation: string;
}

export interface GainPreset {
  readonly id: string;
  readonly label: string;
  /** m² per person. */
  readonly areaPerPerson: PresetDensity;
  /** W per person, sensible only. */
  readonly sensiblePerPerson: PresetDensity;
  /** W/m². */
  readonly lighting: PresetDensity;
  /** W/m². */
  readonly miscEquipment: PresetDensity;
  /** W/m². Zero where the sheet was blank — see the note in the importer. */
  readonly itEquipment: PresetDensity;
  readonly notes: string;
}

/**
 * True while the presets below borrow the office schedule. The UI renders a
 * line saying so; delete this flag when sheet 2 lands and the schedules become
 * per-type.
 */
export const SCHEDULES_ARE_PROVISIONAL = true;

export const GAIN_PRESETS: readonly GainPreset[] = Object.freeze([
  {
    id: "assembly",
    label: "Assembly",
    areaPerPerson: { value: 4.645152, citation: "Standard 90.1 User Manual" },
    sensiblePerPerson: { value: 73.267768, citation: "ASHRAE Handbook Fundamentals" },
    lighting: { value: 8.180572, citation: "ASHRAE 90.1 Building Area Method" },
    miscEquipment: { value: 2.690978, citation: "Standard 90.1 User Manual" },
    itEquipment: { value: 0, citation: "No published default exists — pick an IT space type or enter a value" },
    notes: "",
  },
  {
    id: "healthcare",
    label: "Healthcare",
    areaPerPerson: { value: 18.580608, citation: "Standard 90.1 User Manual" },
    sensiblePerPerson: { value: 58.614214, citation: "ASHRAE Handbook Fundamentals" },
    lighting: { value: 8.718767, citation: "ASHRAE 90.1 Building Area Method" },
    miscEquipment: { value: 10.76391, citation: "Standard 90.1 User Manual" },
    itEquipment: { value: 0, citation: "No published default exists — pick an IT space type or enter a value" },
    notes: "",
  },
  {
    id: "hotel",
    label: "Hotel",
    areaPerPerson: { value: 23.22576, citation: "Standard 90.1 User Manual" },
    sensiblePerPerson: { value: 58.614214, citation: "ASHRAE Handbook Fundamentals" },
    lighting: { value: 6.02779, citation: "ASHRAE 90.1 Building Area Method" },
    miscEquipment: { value: 2.690978, citation: "Standard 90.1 User Manual" },
    itEquipment: { value: 0, citation: "No published default exists — pick an IT space type or enter a value" },
    notes: "",
  },
  {
    id: "manufacturing",
    label: "Light Manufacturing",
    areaPerPerson: { value: 69.67728, citation: "Standard 90.1 User Manual" },
    sensiblePerPerson: { value: 73.267768, citation: "ASHRAE Handbook Fundamentals" },
    lighting: { value: 8.826407, citation: "ASHRAE 90.1 Building Area Method" },
    miscEquipment: { value: 2.152782, citation: "Standard 90.1 User Manual" },
    itEquipment: { value: 0, citation: "No published default exists — pick an IT space type or enter a value" },
    notes: "",
  },
  {
    id: "office",
    label: "Office",
    areaPerPerson: { value: 25.548336, citation: "Standard 90.1 User Manual" },
    sensiblePerPerson: { value: 58.614214, citation: "ASHRAE Handbook Fundamentals" },
    lighting: { value: 6.888903, citation: "ASHRAE 90.1 Building Area Method" },
    miscEquipment: { value: 8.072933, citation: "Standard 90.1 User Manual" },
    itEquipment: { value: 0, citation: "No published default exists — pick an IT space type or enter a value" },
    notes: "",
  },
  {
    id: "restaurant",
    label: "Restaurant",
    areaPerPerson: { value: 9.290304, citation: "Standard 90.1 User Manual" },
    sensiblePerPerson: { value: 73.267768, citation: "ASHRAE Handbook Fundamentals" },
    lighting: { value: 8.611128, citation: "ASHRAE 90.1 Building Area Method" },
    miscEquipment: { value: 10.76391, citation: "Standard 90.1 User Manual" },
    itEquipment: { value: 0, citation: "No published default exists — pick an IT space type or enter a value" },
    notes: "",
  },
  {
    id: "retail",
    label: "Retail",
    areaPerPerson: { value: 27.870912, citation: "Standard 90.1 User Manual" },
    sensiblePerPerson: { value: 58.614214, citation: "ASHRAE Handbook Fundamentals" },
    lighting: { value: 9.041685, citation: "ASHRAE 90.1 Building Area Method" },
    miscEquipment: { value: 2.690978, citation: "Standard 90.1 User Manual" },
    itEquipment: { value: 0, citation: "No published default exists — pick an IT space type or enter a value" },
    notes: "",
  },
  {
    id: "school",
    label: "School",
    areaPerPerson: { value: 6.967728, citation: "Standard 90.1 User Manual" },
    sensiblePerPerson: { value: 58.614214, citation: "ASHRAE Handbook Fundamentals" },
    lighting: { value: 7.750015, citation: "ASHRAE 90.1 Building Area Method" },
    miscEquipment: { value: 5.381955, citation: "Standard 90.1 User Manual" },
    itEquipment: { value: 0, citation: "No published default exists — pick an IT space type or enter a value" },
    notes: "",
  },
  {
    id: "warehouse",
    label: "Warehouse",
    areaPerPerson: { value: 139.35456, citation: "Standard 90.1 User Manual" },
    sensiblePerPerson: { value: 73.267768, citation: "ASHRAE Handbook Fundamentals" },
    lighting: { value: 4.84376, citation: "ASHRAE 90.1 Building Area Method" },
    miscEquipment: { value: 1.076391, citation: "Standard 90.1 User Manual" },
    itEquipment: { value: 0, citation: "No published default exists — pick an IT space type or enter a value" },
    notes: "",
  },
  {
    id: "residential-single",
    label: "Single Family Home",
    areaPerPerson: { value: 69.67728, citation: "Standard 90.1 User Manual" },
    sensiblePerPerson: { value: 58.614214, citation: "ASHRAE Handbook Fundamentals" },
    lighting: { value: 4.84376, citation: "ASHRAE 90.1 Building Area Method" },
    miscEquipment: { value: 5.381955, citation: "Standard 90.1 User Manual" },
    itEquipment: { value: 0, citation: "No published default exists — pick an IT space type or enter a value" },
    notes: "",
  },
  {
    id: "residential-multi",
    label: "Multi-Family",
    areaPerPerson: { value: 55.741824, citation: "Standard 90.1 User Manual" },
    sensiblePerPerson: { value: 58.614214, citation: "ASHRAE Handbook Fundamentals" },
    lighting: { value: 4.84376, citation: "ASHRAE 90.1 Building Area Method" },
    miscEquipment: { value: 5.381955, citation: "Standard 90.1 User Manual" },
    itEquipment: { value: 0, citation: "No published default exists — pick an IT space type or enter a value" },
    notes: "",
  },
  {
    id: "library",
    label: "Library",
    areaPerPerson: { value: 25.548336, citation: "Standard 90.1 User Manual" },
    sensiblePerPerson: { value: 58.614214, citation: "ASHRAE Handbook Fundamentals" },
    lighting: { value: 8.934046, citation: "ASHRAE 90.1 Building Area Method" },
    miscEquipment: { value: 8.072933, citation: "Standard 90.1 User Manual" },
    itEquipment: { value: 0, citation: "No published default exists — pick an IT space type or enter a value" },
    notes: "",
  },
  {
    id: "laboratory",
    label: "Laboratory",
    areaPerPerson: { value: 23.22576, citation: "Standard 90.1 User Manual" },
    sensiblePerPerson: { value: 58.614214, citation: "ASHRAE Handbook Fundamentals" },
    lighting: { value: 9.795158, citation: "ASHRAE 90.1 Building Area Method" },
    miscEquipment: { value: 21.527821, citation: "Standard 90.1 User Manual" },
    itEquipment: { value: 0, citation: "No published default exists — pick an IT space type or enter a value" },
    notes: "",
  },
]);

/** The one the tool opens on. */
export const DEFAULT_PRESET_ID = 'office';

export function presetById(id: string): GainPreset | undefined {
  return GAIN_PRESETS.find((p) => p.id === id);
}
